//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprovedTransportManager.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprovedTransportManager.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City settings.
        /// </summary>
        internal static string itm_citySettings_title {
            get {
                return ResourceManager.GetString("itm_citySettings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N/A.
        /// </summary>
        internal static string itm_common_notApplicableAcronym {
            get {
                return ResourceManager.GetString("itm_common_notApplicableAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Day {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Day_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Day_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day and Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_DayNight {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_DayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a D &amp; N.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_DayNight_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_DayNight_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Night {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Night_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Night_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disabled.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_None {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disab..
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_None_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_None_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identifier.
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_Identifier {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passengers/Capacity.
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_PassengerCapacity {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_PassengerCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (All Time).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitAllTime {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (Current Period).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitCurrentWeek {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitCurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (Last Period).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitLastWeek {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When enabling the express lines, the buses won&apos;t unbunch in the regular stops anymore once it would be done only in terminal stops.
        ///You can disable the unbunching also in terminal stops to get a more fluid line dynamic..
        /// </summary>
        internal static string itm_expressData_disableUnbunchingDescription {
            get {
                return ResourceManager.GetString("itm_expressData_disableUnbunchingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disable unbunching also in terminal stops.
        /// </summary>
        internal static string itm_expressData_disableUnbunchingTerminals {
            get {
                return ResourceManager.GetString("itm_expressData_disableUnbunchingTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express buses.
        /// </summary>
        internal static string itm_expressData_expressBuses {
            get {
                return ResourceManager.GetString("itm_expressData_expressBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express trams.
        /// </summary>
        internal static string itm_expressData_expressTrams {
            get {
                return ResourceManager.GetString("itm_expressData_expressTrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express trolleybuses.
        /// </summary>
        internal static string itm_expressData_expressTrolleybus {
            get {
                return ResourceManager.GetString("itm_expressData_expressTrolleybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express lines.
        /// </summary>
        internal static string itm_expressData_title {
            get {
                return ResourceManager.GetString("itm_expressData_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EAT:.
        /// </summary>
        internal static string itm_lineMap_earningsAllTimeAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsAllTimeAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EAT - Earnings all time.
        /// </summary>
        internal static string itm_lineMap_earningsAllTimeAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsAllTimeAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECP:.
        /// </summary>
        internal static string itm_lineMap_earningsCurrentPeriodAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsCurrentPeriodAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECP - Earnings current period.
        /// </summary>
        internal static string itm_lineMap_earningsCurrentPeriodAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsCurrentPeriodAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ELP:.
        /// </summary>
        internal static string itm_lineMap_earningsLastPeriodAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsLastPeriodAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ELP - Earnings last period.
        /// </summary>
        internal static string itm_lineMap_earningsLastPeriodAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsLastPeriodAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line stops map.
        /// </summary>
        internal static string itm_lineMap_title {
            get {
                return ResourceManager.GetString("itm_lineMap_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicle data to show.
        /// </summary>
        internal static string itm_lineMap_vehicleDataToShow {
            get {
                return ResourceManager.GetString("itm_lineMap_vehicleDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#{3}&gt;Residents: {0:N0}; Tourists: {1:N0}; {2:N0}% Bored&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineMap_waitingTemplate {
            get {
                return ResourceManager.GetString("itm_lineMap_waitingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Activ..
        /// </summary>
        internal static string itm_linesListingWindow_activityColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_activityColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balance.
        /// </summary>
        internal static string itm_linesListingWindow_balanceColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_balanceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bdgt..
        /// </summary>
        internal static string itm_linesListingWindow_budgetColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_budgetColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lines from type &lt;color=yellow&gt;{0}&lt;/color&gt;: {1:N0} - Total transport lines in the city: {2:N0}.
        /// </summary>
        internal static string itm_linesListingWindow_footerFormat {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_footerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Name.
        /// </summary>
        internal static string itm_linesListingWindow_nameColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_nameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pass..
        /// </summary>
        internal static string itm_linesListingWindow_passengersColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_passengersColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stops.
        /// </summary>
        internal static string itm_linesListingWindow_stopsColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_stopsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no lines in this city!.
        /// </summary>
        internal static string itm_linesListingWindow_thereAreNoLinesInCity {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_thereAreNoLinesInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Public Transport Lines.
        /// </summary>
        internal static string itm_linesListingWindow_tilte {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_tilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Veh..
        /// </summary>
        internal static string itm_linesListingWindow_vehiclesColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_vehiclesColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adult.
        /// </summary>
        internal static string itm_lineView_adultLbl {
            get {
                return ResourceManager.GetString("itm_lineView_adultLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Budget View.
        /// </summary>
        internal static string itm_lineView_budgetViewBtn {
            get {
                return ResourceManager.GetString("itm_lineView_budgetViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Children.
        /// </summary>
        internal static string itm_lineView_childrenLbl {
            get {
                return ResourceManager.GetString("itm_lineView_childrenLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day:.
        /// </summary>
        internal static string itm_lineView_dayBudgetTitle {
            get {
                return ResourceManager.GetString("itm_lineView_dayBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete line.
        /// </summary>
        internal static string itm_lineView_deleteLine {
            get {
                return ResourceManager.GetString("itm_lineView_deleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:N1}m - {1} Stops - {2}% Trips saved.
        /// </summary>
        internal static string itm_lineView_distanceStops {
            get {
                return ResourceManager.GetString("itm_lineView_distanceStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Activity.
        /// </summary>
        internal static string itm_lineView_lineActivity {
            get {
                return ResourceManager.GetString("itm_lineView_lineActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Budget (%).
        /// </summary>
        internal static string itm_lineView_lineBudget {
            get {
                return ResourceManager.GetString("itm_lineView_lineBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Color.
        /// </summary>
        internal static string itm_lineView_lineColor {
            get {
                return ResourceManager.GetString("itm_lineView_lineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal line number.
        /// </summary>
        internal static string itm_lineView_lineInternalNumber {
            get {
                return ResourceManager.GetString("itm_lineView_lineInternalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lines Overview.
        /// </summary>
        internal static string itm_lineView_linesListBtn {
            get {
                return ResourceManager.GetString("itm_lineView_linesListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night:.
        /// </summary>
        internal static string itm_lineView_nightBudgetTitle {
            get {
                return ResourceManager.GetString("itm_lineView_nightBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:N0} Residents / {1:N0} Tourists.
        /// </summary>
        internal static string itm_lineView_residentTourists {
            get {
                return ResourceManager.GetString("itm_lineView_residentTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senior.
        /// </summary>
        internal static string itm_lineView_seniorLbl {
            get {
                return ResourceManager.GetString("itm_lineView_seniorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Teen.
        /// </summary>
        internal static string itm_lineView_teenLbl {
            get {
                return ResourceManager.GetString("itm_lineView_teenLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=yellow&gt;{0} of {1} stops of this line aren&apos;t charging fees due stops&apos; district policies. The line might not have any earnings!&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineView_thereAreFreeStops {
            get {
                return ResourceManager.GetString("itm_lineView_thereAreFreeStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=red&gt;This line is broken!&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineView_thisLineIsBroken {
            get {
                return ResourceManager.GetString("itm_lineView_thisLineIsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket Price (in cents).
        /// </summary>
        internal static string itm_lineView_ticketPrice {
            get {
                return ResourceManager.GetString("itm_lineView_ticketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Weekly report data.
        /// </summary>
        internal static string itm_lineView_weeklyDataTitle {
            get {
                return ResourceManager.GetString("itm_lineView_weeklyDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Young.
        /// </summary>
        internal static string itm_lineView_youngLbl {
            get {
                return ResourceManager.GetString("itm_lineView_youngLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current line exclusive.
        /// </summary>
        internal static string itm_vehicleSelectWindow_defaultGroupText {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_defaultGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicles models for line selection.
        /// </summary>
        internal static string itm_vehicleSelectWindow_title {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extends the public transport lines management in Cities: Skylines.
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
    }
}
