//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprovedTransportManager.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprovedTransportManager.Localization.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City settings.
        /// </summary>
        internal static string itm_citySettings_title {
            get {
                return ResourceManager.GetString("itm_citySettings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear.
        /// </summary>
        internal static string itm_common_clear {
            get {
                return ResourceManager.GetString("itm_common_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy.
        /// </summary>
        internal static string itm_common_copy {
            get {
                return ResourceManager.GetString("itm_common_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a N/A.
        /// </summary>
        internal static string itm_common_notApplicableAcronym {
            get {
                return ResourceManager.GetString("itm_common_notApplicableAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paste.
        /// </summary>
        internal static string itm_common_paste {
            get {
                return ResourceManager.GetString("itm_common_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Day {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Day_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Day_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day and Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_DayNight {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_DayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a D &amp; N.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_DayNight_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_DayNight_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Night {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_Night_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_Night_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disabled.
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_None {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disab..
        /// </summary>
        internal static string itm_Enum__LineActivityOptions_None_SHORT {
            get {
                return ResourceManager.GetString("itm_Enum__LineActivityOptions_None_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identifier.
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_Identifier {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passengers/Capacity.
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_PassengerCapacity {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_PassengerCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (All Time).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitAllTime {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitAllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (Current Period).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitCurrentWeek {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitCurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profit (Last Period).
        /// </summary>
        internal static string itm_Enum__VehicleShowDataType_ProfitLastWeek {
            get {
                return ResourceManager.GetString("itm_Enum__VehicleShowDataType_ProfitLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a When enabling the express lines, the buses won&apos;t unbunch in the regular stops anymore once it would be done only in terminal stops.
        ///You can disable the unbunching also in terminal stops to get a more fluid line dynamic..
        /// </summary>
        internal static string itm_expressData_disableUnbunchingDescription {
            get {
                return ResourceManager.GetString("itm_expressData_disableUnbunchingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disable unbunching also in terminal stops.
        /// </summary>
        internal static string itm_expressData_disableUnbunchingTerminals {
            get {
                return ResourceManager.GetString("itm_expressData_disableUnbunchingTerminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express buses.
        /// </summary>
        internal static string itm_expressData_expressBuses {
            get {
                return ResourceManager.GetString("itm_expressData_expressBuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express trams.
        /// </summary>
        internal static string itm_expressData_expressTrams {
            get {
                return ResourceManager.GetString("itm_expressData_expressTrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express trolleybuses.
        /// </summary>
        internal static string itm_expressData_expressTrolleybus {
            get {
                return ResourceManager.GetString("itm_expressData_expressTrolleybus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Express lines.
        /// </summary>
        internal static string itm_expressData_title {
            get {
                return ResourceManager.GetString("itm_expressData_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assets settings.
        /// </summary>
        internal static string itm_generalSettings_assetsSettings {
            get {
                return ResourceManager.GetString("itm_generalSettings_assetsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The assets settings were exported to file:
        ///&lt;color=yellow&gt;{0}&lt;/color&gt;.
        /// </summary>
        internal static string itm_generalSettings_defaultAssetFileExportedMessage {
            get {
                return ResourceManager.GetString("itm_generalSettings_defaultAssetFileExportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The asset settings were loaded successfully from default settings file.
        ///You may need to reload all files to see the new values being used.
        /// </summary>
        internal static string itm_generalSettings_defaultAssetFileImportedMessage {
            get {
                return ResourceManager.GetString("itm_generalSettings_defaultAssetFileImportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The city settings were exported to file:
        ///&lt;color=yellow&gt;{0}&lt;/color&gt;.
        /// </summary>
        internal static string itm_generalSettings_defaultCityFileExportedMessage {
            get {
                return ResourceManager.GetString("itm_generalSettings_defaultCityFileExportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The city settings were loaded successfully from default settings file..
        /// </summary>
        internal static string itm_generalSettings_defaultCityFileImportedMessage {
            get {
                return ResourceManager.GetString("itm_generalSettings_defaultCityFileImportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General settings.
        /// </summary>
        internal static string itm_generalSettings_defaultGeneralSettings {
            get {
                return ResourceManager.GetString("itm_generalSettings_defaultGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expert mode
        ///Shows advanced settings and extra windows for deep setup
        ///Recomended for experenced players only.
        /// </summary>
        internal static string itm_generalSettings_expertMode {
            get {
                return ResourceManager.GetString("itm_generalSettings_expertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Export as default.
        /// </summary>
        internal static string itm_generalSettings_exportCurrentToFile {
            get {
                return ResourceManager.GetString("itm_generalSettings_exportCurrentToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Import from default.
        /// </summary>
        internal static string itm_generalSettings_importCurrentFromFile {
            get {
                return ResourceManager.GetString("itm_generalSettings_importCurrentFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General.
        /// </summary>
        internal static string itm_generalSettings_title {
            get {
                return ResourceManager.GetString("itm_generalSettings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go to maintenance screen.
        /// </summary>
        internal static string itm_goToMaintenanceCostScreen {
            get {
                return ResourceManager.GetString("itm_goToMaintenanceCostScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Change custom logo.
        /// </summary>
        internal static string itm_lineLogo_changeCustomLogo {
            get {
                return ResourceManager.GetString("itm_lineLogo_changeCustomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=red&gt;Remove custom logo&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineLogo_deleteCustomLogo {
            get {
                return ResourceManager.GetString("itm_lineLogo_deleteCustomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid texture!.
        /// </summary>
        internal static string itm_lineLogo_invalidTexture {
            get {
                return ResourceManager.GetString("itm_lineLogo_invalidTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The texture must have exactly 256x256 pixels as dimensions!.
        /// </summary>
        internal static string itm_lineLogo_invalidTextureContent {
            get {
                return ResourceManager.GetString("itm_lineLogo_invalidTextureContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set custom logo.
        /// </summary>
        internal static string itm_lineLogo_setCustomLogo {
            get {
                return ResourceManager.GetString("itm_lineLogo_setCustomLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E16:.
        /// </summary>
        internal static string itm_lineMap_earningsAllTimeAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsAllTimeAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E16 - Earnings last 16 weeks (24h for Real Time).
        /// </summary>
        internal static string itm_lineMap_earningsAllTimeAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsAllTimeAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECP:.
        /// </summary>
        internal static string itm_lineMap_earningsCurrentPeriodAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsCurrentPeriodAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECP - Earnings current period.
        /// </summary>
        internal static string itm_lineMap_earningsCurrentPeriodAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsCurrentPeriodAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ELP:.
        /// </summary>
        internal static string itm_lineMap_earningsLastPeriodAcronym {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsLastPeriodAcronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ELP - Earnings last period.
        /// </summary>
        internal static string itm_lineMap_earningsLastPeriodAcronymLegend {
            get {
                return ResourceManager.GetString("itm_lineMap_earningsLastPeriodAcronymLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erase all custom stop names.
        /// </summary>
        internal static string itm_lineMap_eraseAllCustomStopNames {
            get {
                return ResourceManager.GetString("itm_lineMap_eraseAllCustomStopNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current stop isn&apos;t inside a district. Ensure it belongs to a district to bind its name to it..
        /// </summary>
        internal static string itm_lineMap_failedSettingDistrict {
            get {
                return ResourceManager.GetString("itm_lineMap_failedSettingDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The current stop isn&apos;t inside a special area. Ensure it belongs to a special area to bind its name to it..
        /// </summary>
        internal static string itm_lineMap_failedSettingPark {
            get {
                return ResourceManager.GetString("itm_lineMap_failedSettingPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force bind stop name to building (pick).
        /// </summary>
        internal static string itm_lineMap_forceBindToBuilding {
            get {
                return ResourceManager.GetString("itm_lineMap_forceBindToBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force bind stop name to district.
        /// </summary>
        internal static string itm_lineMap_forceBindToDistrict {
            get {
                return ResourceManager.GetString("itm_lineMap_forceBindToDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force bind stop name to special area.
        /// </summary>
        internal static string itm_lineMap_forceBindToPark {
            get {
                return ResourceManager.GetString("itm_lineMap_forceBindToPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force bind stop name to road (pick).
        /// </summary>
        internal static string itm_lineMap_forceBindToRoad {
            get {
                return ResourceManager.GetString("itm_lineMap_forceBindToRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculate all stops names bindings.
        /// </summary>
        internal static string itm_lineMap_recalculateAllStopNames {
            get {
                return ResourceManager.GetString("itm_lineMap_recalculateAllStopNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalculate stop name bind.
        /// </summary>
        internal static string itm_lineMap_recalculateAutoBind {
            get {
                return ResourceManager.GetString("itm_lineMap_recalculateAutoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line stops map.
        /// </summary>
        internal static string itm_lineMap_title {
            get {
                return ResourceManager.GetString("itm_lineMap_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicle data to show.
        /// </summary>
        internal static string itm_lineMap_vehicleDataToShow {
            get {
                return ResourceManager.GetString("itm_lineMap_vehicleDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#{3}&gt;Residents: {0:N0}; Tourists: {1:N0}; {2:N0}% Bored&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineMap_waitingTemplate {
            get {
                return ResourceManager.GetString("itm_lineMap_waitingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Activ..
        /// </summary>
        internal static string itm_linesListingWindow_activityColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_activityColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balance.
        /// </summary>
        internal static string itm_linesListingWindow_balanceColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_balanceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bdgt..
        /// </summary>
        internal static string itm_linesListingWindow_budgetColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_budgetColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lines from type &lt;color=yellow&gt;{0}&lt;/color&gt;: {1:N0} - Total transport lines in the city: {2:N0}.
        /// </summary>
        internal static string itm_linesListingWindow_footerFormat {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_footerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Name.
        /// </summary>
        internal static string itm_linesListingWindow_nameColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_nameColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pass..
        /// </summary>
        internal static string itm_linesListingWindow_passengersColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_passengersColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stops.
        /// </summary>
        internal static string itm_linesListingWindow_stopsColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_stopsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no lines in this city!.
        /// </summary>
        internal static string itm_linesListingWindow_thereAreNoLinesInCity {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_thereAreNoLinesInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Public Transport Lines.
        /// </summary>
        internal static string itm_linesListingWindow_tilte {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_tilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Veh..
        /// </summary>
        internal static string itm_linesListingWindow_vehiclesColumnTitle {
            get {
                return ResourceManager.GetString("itm_linesListingWindow_vehiclesColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adult.
        /// </summary>
        internal static string itm_lineView_adultLbl {
            get {
                return ResourceManager.GetString("itm_lineView_adultLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Budget View.
        /// </summary>
        internal static string itm_lineView_budgetViewBtn {
            get {
                return ResourceManager.GetString("itm_lineView_budgetViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Children.
        /// </summary>
        internal static string itm_lineView_childrenLbl {
            get {
                return ResourceManager.GetString("itm_lineView_childrenLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Day:.
        /// </summary>
        internal static string itm_lineView_dayBudgetTitle {
            get {
                return ResourceManager.GetString("itm_lineView_dayBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete line.
        /// </summary>
        internal static string itm_lineView_deleteLine {
            get {
                return ResourceManager.GetString("itm_lineView_deleteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:N1}m - {1} Stops - {2}% Trips saved.
        /// </summary>
        internal static string itm_lineView_distanceStops {
            get {
                return ResourceManager.GetString("itm_lineView_distanceStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Activity.
        /// </summary>
        internal static string itm_lineView_lineActivity {
            get {
                return ResourceManager.GetString("itm_lineView_lineActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Budget (%).
        /// </summary>
        internal static string itm_lineView_lineBudget {
            get {
                return ResourceManager.GetString("itm_lineView_lineBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line Color.
        /// </summary>
        internal static string itm_lineView_lineColor {
            get {
                return ResourceManager.GetString("itm_lineView_lineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal line number.
        /// </summary>
        internal static string itm_lineView_lineInternalNumber {
            get {
                return ResourceManager.GetString("itm_lineView_lineInternalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line name.
        /// </summary>
        internal static string itm_lineView_lineName {
            get {
                return ResourceManager.GetString("itm_lineView_lineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lines Overview.
        /// </summary>
        internal static string itm_lineView_linesListBtn {
            get {
                return ResourceManager.GetString("itm_lineView_linesListBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Night:.
        /// </summary>
        internal static string itm_lineView_nightBudgetTitle {
            get {
                return ResourceManager.GetString("itm_lineView_nightBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=red&gt;Remove stop&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineView_removeStop {
            get {
                return ResourceManager.GetString("itm_lineView_removeStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0:N0} Residents / {1:N0} Tourists.
        /// </summary>
        internal static string itm_lineView_residentTourists {
            get {
                return ResourceManager.GetString("itm_lineView_residentTourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senior.
        /// </summary>
        internal static string itm_lineView_seniorLbl {
            get {
                return ResourceManager.GetString("itm_lineView_seniorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set as first stop.
        /// </summary>
        internal static string itm_lineView_setAsFirstStop {
            get {
                return ResourceManager.GetString("itm_lineView_setAsFirstStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Set as terminus.
        /// </summary>
        internal static string itm_lineView_setAsTerminus {
            get {
                return ResourceManager.GetString("itm_lineView_setAsTerminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Teen.
        /// </summary>
        internal static string itm_lineView_teenLbl {
            get {
                return ResourceManager.GetString("itm_lineView_teenLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=yellow&gt;{0} of {1} stops of this line aren&apos;t charging fees due stops&apos; district policies. The line might not have any earnings!&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineView_thereAreFreeStops {
            get {
                return ResourceManager.GetString("itm_lineView_thereAreFreeStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=red&gt;This line is broken!&lt;/color&gt;.
        /// </summary>
        internal static string itm_lineView_thisLineIsBroken {
            get {
                return ResourceManager.GetString("itm_lineView_thisLineIsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket Price (in cents).
        /// </summary>
        internal static string itm_lineView_ticketPrice {
            get {
                return ResourceManager.GetString("itm_lineView_ticketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remove terminus.
        /// </summary>
        internal static string itm_lineView_unsetAsTerminus {
            get {
                return ResourceManager.GetString("itm_lineView_unsetAsTerminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Weekly report data.
        /// </summary>
        internal static string itm_lineView_weeklyDataTitle {
            get {
                return ResourceManager.GetString("itm_lineView_weeklyDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Young.
        /// </summary>
        internal static string itm_lineView_youngLbl {
            get {
                return ResourceManager.GetString("itm_lineView_youngLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=yellow&gt;{0}&lt;/color&gt; (Default: {1:N0}¢/kpax).
        /// </summary>
        internal static string itm_maintenanceData_defaultMaintenanceFormat {
            get {
                return ResourceManager.GetString("itm_maintenanceData_defaultMaintenanceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The maintenance cost is based in a cost in cents per passenger ratio. Higher capacities means higher costs!
        ///Left it at &quot;0&quot; to use the default cost..
        /// </summary>
        internal static string itm_maintenanceData_header {
            get {
                return ResourceManager.GetString("itm_maintenanceData_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maintenance costs.
        /// </summary>
        internal static string itm_maintenanceData_title {
            get {
                return ResourceManager.GetString("itm_maintenanceData_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There are no lines around here....
        /// </summary>
        internal static string itm_nearLines_noNearLinesHere {
            get {
                return ResourceManager.GetString("itm_nearLines_noNearLinesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Near lines.
        /// </summary>
        internal static string itm_nearLines_title {
            get {
                return ResourceManager.GetString("itm_nearLines_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Get a logo image for line: {0}.
        /// </summary>
        internal static string itm_pickALogoForLine {
            get {
                return ResourceManager.GetString("itm_pickALogoForLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All line infos that (possibly) can create a line tool are available below. Use by your own risk to create special lines in these modals.
        ///&lt;color=red&gt;IT MAY BE NOT STABLE! BEWARE!&lt;/color&gt;.
        /// </summary>
        internal static string itm_specialLineTools_header {
            get {
                return ResourceManager.GetString("itm_specialLineTools_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Line tools.
        /// </summary>
        internal static string itm_specialLineTools_title {
            get {
                return ResourceManager.GetString("itm_specialLineTools_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear filters.
        /// </summary>
        internal static string itm_statistics_clearFilters {
            get {
                return ResourceManager.GetString("itm_statistics_clearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=#FF00FF&gt;--TRANSPORT LINE--&lt;/color&gt;.
        /// </summary>
        internal static string itm_statistics_nullSelLine {
            get {
                return ResourceManager.GetString("itm_statistics_nullSelLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=yellow&gt;--ALL STOPS--&lt;/color&gt;.
        /// </summary>
        internal static string itm_statistics_nullSelStop {
            get {
                return ResourceManager.GetString("itm_statistics_nullSelStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;color=yellow&gt;--ALL VEHICLES--&lt;/color&gt;.
        /// </summary>
        internal static string itm_statistics_nullVehicle {
            get {
                return ResourceManager.GetString("itm_statistics_nullVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reload lines.
        /// </summary>
        internal static string itm_statistics_reloadLines {
            get {
                return ResourceManager.GetString("itm_statistics_reloadLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select line.
        /// </summary>
        internal static string itm_statistics_selectLine {
            get {
                return ResourceManager.GetString("itm_statistics_selectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop.
        /// </summary>
        internal static string itm_statistics_stop {
            get {
                return ResourceManager.GetString("itm_statistics_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All vehicles and stops.
        /// </summary>
        internal static string itm_statistics_subtitleTableFormatAll {
            get {
                return ResourceManager.GetString("itm_statistics_subtitleTableFormatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Statistics @ Stop {0}.
        /// </summary>
        internal static string itm_statistics_subtitleTableFormatStops {
            get {
                return ResourceManager.GetString("itm_statistics_subtitleTableFormatStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Statistics @ Vehicle {0}.
        /// </summary>
        internal static string itm_statistics_subtitleTableFormatVehicles {
            get {
                return ResourceManager.GetString("itm_statistics_subtitleTableFormatVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Statistics.
        /// </summary>
        internal static string itm_statistics_title {
            get {
                return ResourceManager.GetString("itm_statistics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicle.
        /// </summary>
        internal static string itm_statistics_vehicle {
            get {
                return ResourceManager.GetString("itm_statistics_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Since {0}.
        /// </summary>
        internal static string itm_statisticsTable_currentLineColumnValue {
            get {
                return ResourceManager.GetString("itm_statisticsTable_currentLineColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This data is not available in current selected filter.
        /// </summary>
        internal static string itm_statisticsTable_dataNotAvailableForThisFilter {
            get {
                return ResourceManager.GetString("itm_statisticsTable_dataNotAvailableForThisFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Balance.
        /// </summary>
        internal static string itm_statisticsTable_financeReport_balance {
            get {
                return ResourceManager.GetString("itm_statisticsTable_financeReport_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expense.
        /// </summary>
        internal static string itm_statisticsTable_financeReport_expense {
            get {
                return ResourceManager.GetString("itm_statisticsTable_financeReport_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Income.
        /// </summary>
        internal static string itm_statisticsTable_financeReport_income {
            get {
                return ResourceManager.GetString("itm_statisticsTable_financeReport_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Financial report.
        /// </summary>
        internal static string itm_statisticsTable_financeReport_title {
            get {
                return ResourceManager.GetString("itm_statisticsTable_financeReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adults.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_adult {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Children.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_child {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seniors.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_elder {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_elder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Teens.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_teen {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_teen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Passenger age report.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_title {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_total {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Youngs.
        /// </summary>
        internal static string itm_statisticsTable_passengerAgeReport_young {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerAgeReport_young", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Females.
        /// </summary>
        internal static string itm_statisticsTable_passengerGenderReport_female {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerGenderReport_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Males.
        /// </summary>
        internal static string itm_statisticsTable_passengerGenderReport_male {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerGenderReport_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gender Report.
        /// </summary>
        internal static string itm_statisticsTable_passengerGenderReport_title {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerGenderReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string itm_statisticsTable_passengerGenderReport_total {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerGenderReport_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Students.
        /// </summary>
        internal static string itm_statisticsTable_passengerStudentsTouristsReport_students {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerStudentsTouristsReport_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Students &amp; Tourists.
        /// </summary>
        internal static string itm_statisticsTable_passengerStudentsTouristsReport_title {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerStudentsTouristsReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string itm_statisticsTable_passengerStudentsTouristsReport_total {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerStudentsTouristsReport_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tourists.
        /// </summary>
        internal static string itm_statisticsTable_passengerStudentsTouristsReport_tourists {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerStudentsTouristsReport_tourists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a High Wealth.
        /// </summary>
        internal static string itm_statisticsTable_passengerWealthReport_high {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerWealthReport_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Low Wealth.
        /// </summary>
        internal static string itm_statisticsTable_passengerWealthReport_low {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerWealthReport_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medium Wealth.
        /// </summary>
        internal static string itm_statisticsTable_passengerWealthReport_medium {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerWealthReport_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wealth Report.
        /// </summary>
        internal static string itm_statisticsTable_passengerWealthReport_title {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerWealthReport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string itm_statisticsTable_passengerWealthReport_total {
            get {
                return ResourceManager.GetString("itm_statisticsTable_passengerWealthReport_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Period.
        /// </summary>
        internal static string itm_statisticsTable_periodTitle {
            get {
                return ResourceManager.GetString("itm_statisticsTable_periodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total last 16 weeks.
        /// </summary>
        internal static string itm_statisticsTable_totalLast16w {
            get {
                return ResourceManager.GetString("itm_statisticsTable_totalLast16w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total last 24h.
        /// </summary>
        internal static string itm_statisticsTable_totalLast24h {
            get {
                return ResourceManager.GetString("itm_statisticsTable_totalLast24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicle (activate/deactivate).
        /// </summary>
        internal static string itm_vehicleSelectWindow_assetNameOnOff {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_assetNameOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capacity.
        /// </summary>
        internal static string itm_vehicleSelectWindow_capacity {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cost/Period.
        /// </summary>
        internal static string itm_vehicleSelectWindow_costPeriod {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_costPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Current line exclusive.
        /// </summary>
        internal static string itm_vehicleSelectWindow_defaultGroupText {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_defaultGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the assets allowed to spawn in the line in this window.
        ///The new selection will be used as reference when spawning new vehicles to the line.
        ///The vehicles in the line that aren&apos;t selected in this list will be sent to depot as soon it:
        ///- Reach next stop (non-road based transport types only)
        ///- Get emptied
        ///- Reach the first stop or any terminal stop (road-based modals only)
        ///
        ///The capacity can be edited here also, the maintenance cost is calculated based in the cost for each 1000 passengers setted up [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string itm_vehicleSelectWindow_helpContent {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_helpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vehicles models for line selection.
        /// </summary>
        internal static string itm_vehicleSelectWindow_title {
            get {
                return ResourceManager.GetString("itm_vehicleSelectWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extends the public transport lines management in Cities: Skylines.
        /// </summary>
        internal static string root_modDescription {
            get {
                return ResourceManager.GetString("root_modDescription", resourceCulture);
            }
        }
    }
}
