extern alias UUI;
using static ImprovedTransportManager.TransportSystems.TransportSystemTypeExtensions;

namespace ImprovedTransportManager.TransportSystems
{
    public enum TransportSystemType : uint
    {
        // TransportType << ROLL_TRANSPORT_TYPE | (VehicleTypeBitIdx+1) << ROLL_VEHICLE_TYPE_NTH_BIT | Subservice <<ROLL_SUBSERVICE | CityTransportLevelBitMask << ROLL_CITY_LEVELMASK | InterCityTransportLevel (7 for none)
        // UINT DESIGN BY BIT= 0000000t ttttvvvv vsssssss ccccciii

        BUS = ((TransportInfo.TransportType.Bus & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Car & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportBus & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (((1 << ItemClass.Level.Level1) | (1 << ItemClass.Level.Level2)) << ROLL_CITY_LEVELMASK) | (ItemClass.Level.Level3 & 0x7u),
        BLIMP = ((TransportInfo.TransportType.Airplane & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Blimp & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportPlane & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level2 << ROLL_CITY_LEVELMASK) | (7u),
        BALLOON = ((TransportInfo.TransportType.HotAirBalloon & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.None & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTours & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level4 << ROLL_CITY_LEVELMASK) | (7u),
        CABLE_CAR = ((TransportInfo.TransportType.CableCar & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.CableCar & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportCableCar & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        EVAC_BUS = ((TransportInfo.TransportType.EvacuationBus & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Car & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.None & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level4 << ROLL_CITY_LEVELMASK) | (7u),
        FERRY = ((TransportInfo.TransportType.Ship & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Ferry & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportShip & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level2 << ROLL_CITY_LEVELMASK) | (7u),
        FISHING = ((TransportInfo.TransportType.Fishing & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Ship & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.None & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        HELICOPTER = ((TransportInfo.TransportType.Helicopter & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Helicopter & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportPlane & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level3 << ROLL_CITY_LEVELMASK) | (7u),
        METRO = ((TransportInfo.TransportType.Metro & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Metro & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportMetro & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        MONORAIL = ((TransportInfo.TransportType.Monorail & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Monorail & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportMonorail & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        PLANE = ((TransportInfo.TransportType.Airplane & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Plane & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportPlane & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (ItemClass.Level.Level1 & 7u),
        POST = ((TransportInfo.TransportType.Post & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.None & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportPost & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level2 << ROLL_CITY_LEVELMASK) | (7u),
        SHIP = ((TransportInfo.TransportType.Ship & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Ship & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportShip & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (ItemClass.Level.Level1 & 7u),
        TAXI = ((TransportInfo.TransportType.Taxi & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Car & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTaxi & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        TOUR_BUS = ((TransportInfo.TransportType.TouristBus & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Car & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTours & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level3 << ROLL_CITY_LEVELMASK) | (7u),
        TOUR_PED = ((TransportInfo.TransportType.Pedestrian & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.None & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTours & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level5 << ROLL_CITY_LEVELMASK) | (7u),
        TRAIN = ((TransportInfo.TransportType.Train & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Train & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTrain & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (ItemClass.Level.Level1 & 7u),
        TRAM = ((TransportInfo.TransportType.Tram & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Tram & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTram & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
        TROLLEY = ((TransportInfo.TransportType.Trolleybus & BITMASK_TRANSPORT_TYPE) << ROLL_TRANSPORT_TYPE) | ((TransportSystemVehicleType.Trolleybus & BITMASK_VEHICLE_TYPE_NTH_BIT) << ROLL_VEHICLE_TYPE_NTH_BIT) | ((ItemClass.SubService.PublicTransportTrolleybus & BITMASK_SUBSERVICE) << ROLL_SUBSERVICE) | (1 << ItemClass.Level.Level1 << ROLL_CITY_LEVELMASK) | (7u),
    }
}
